Traceback (most recent call last):
  File "/home/andres/.local/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/home/andres/.local/lib/python3.8/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/andres/.local/lib/python3.8/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/home/andres/.local/lib/python3.8/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/andres/.local/lib/python3.8/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/home/andres/.local/lib/python3.8/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/andres/.local/lib/python3.8/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# celda de c√≥digo para probar
dfr = dfl.pivot_table(index=['profesor', 'IDG'], columns='programa', values=['corte1', 'corte2'], aggfunc=np.mean, margins='All',\
                      margins_name='Total', dropna=True, fill_value=-1)
dfr
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
Input [0;32mIn [80][0m, in [0;36m<cell line: 2>[0;34m()[0m
[1;32m      1[0m [38;5;66;03m# celda de c√≥digo para probar[39;00m
[0;32m----> 2[0m dfr [38;5;241m=[39m [43mdfl[49m[38;5;241m.[39mpivot_table(index[38;5;241m=[39m[[38;5;124m'[39m[38;5;124mprofesor[39m[38;5;124m'[39m, [38;5;124m'[39m[38;5;124mIDG[39m[38;5;124m'[39m], columns[38;5;241m=[39m[38;5;124m'[39m[38;5;124mprograma[39m[38;5;124m'[39m, values[38;5;241m=[39m[[38;5;124m'[39m[38;5;124mcorte1[39m[38;5;124m'[39m, [38;5;124m'[39m[38;5;124mcorte2[39m[38;5;124m'[39m], aggfunc[38;5;241m=[39mnp[38;5;241m.[39mmean, margins[38;5;241m=[39m[38;5;124m'[39m[38;5;124mAll[39m[38;5;124m'[39m,\
[1;32m      3[0m                       margins_name[38;5;241m=[39m[38;5;124m'[39m[38;5;124mTotal[39m[38;5;124m'[39m, dropna[38;5;241m=[39m[38;5;28;01mTrue[39;00m, fill_value[38;5;241m=[39m[38;5;241m-[39m[38;5;241m1[39m)
[1;32m      4[0m dfr

[0;31mNameError[0m: name 'dfl' is not defined
NameError: name 'dfl' is not defined

